# Generated by Django 5.1.7 on 2025-03-15 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('conference', 'Конференция'), ('seminar', 'Семинар'), ('workshop', 'Мастер-класс'), ('other', 'Другое')], max_length=50, verbose_name='Тип мероприятия')),
                ('date', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('description', models.TextField(verbose_name='Описание мероприятия')),
                ('max_participants', models.PositiveIntegerField(verbose_name='Максимальное количество участников')),
                ('participants_count', models.PositiveIntegerField(default=0, verbose_name='Количество участников')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('university', models.CharField(max_length=255, verbose_name='Университет')),
                ('faculty', models.CharField(max_length=255, verbose_name='Факультет')),
                ('group', models.CharField(max_length=50, verbose_name='Группа')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event', verbose_name='Мероприятие')),
            ],
        ),
    ]
